apiVersion: apps/v1
kind: Deployment
metadata:
  name: capstone
  labels:
    app: capstone
  namespace: default
spec:
  replicas: 2
  #progressDeadlineSeconds: 3600
  selector:
    matchLabels:
      app: capstone
  strategy:
    rollingUpdate:
      maxSurge: 1  #25% or 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: capstone
        role: RollingUpdate
    spec:
      containers:
        - image: harshitha95/capstone
          imagePullPolicy: "Always"
          name: capstone
          ports:
            - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: capstone
  labels:
    app: capstone
spec:
  type: LoadBalancer
  selector:
    app: capstone
  ports:
    - port: 8000
      targetPort: 80
      protocol: TCP